//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace TXSeries_DUP001.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BBStudentDataSoap", Namespace="http://tempuri.org/")]
    public partial class BBStudentData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getStudentIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback setStudentIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFirstNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback setFirstNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback setLastNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDOBOperationCompleted;
        
        private System.Threading.SendOrPostCallback setDOBOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGPAOperationCompleted;
        
        private System.Threading.SendOrPostCallback setGPAOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMajorCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback setMajorCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAddDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback setAddDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChangeDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback setChangeDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChangeTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback setChangeTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback setEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BBStudentData() {
            this.Url = global::TXSeries_DUP001.Properties.Settings.Default.TXSeries_DUP001_localhost_BBStudentData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getStudentIDCompletedEventHandler getStudentIDCompleted;
        
        /// <remarks/>
        public event setStudentIDCompletedEventHandler setStudentIDCompleted;
        
        /// <remarks/>
        public event getFirstNameCompletedEventHandler getFirstNameCompleted;
        
        /// <remarks/>
        public event setFirstNameCompletedEventHandler setFirstNameCompleted;
        
        /// <remarks/>
        public event getLastNameCompletedEventHandler getLastNameCompleted;
        
        /// <remarks/>
        public event getEmailCompletedEventHandler getEmailCompleted;
        
        /// <remarks/>
        public event setLastNameCompletedEventHandler setLastNameCompleted;
        
        /// <remarks/>
        public event getDOBCompletedEventHandler getDOBCompleted;
        
        /// <remarks/>
        public event setDOBCompletedEventHandler setDOBCompleted;
        
        /// <remarks/>
        public event getGPACompletedEventHandler getGPACompleted;
        
        /// <remarks/>
        public event setGPACompletedEventHandler setGPACompleted;
        
        /// <remarks/>
        public event getMajorCodeCompletedEventHandler getMajorCodeCompleted;
        
        /// <remarks/>
        public event setMajorCodeCompletedEventHandler setMajorCodeCompleted;
        
        /// <remarks/>
        public event getAddDateCompletedEventHandler getAddDateCompleted;
        
        /// <remarks/>
        public event setAddDateCompletedEventHandler setAddDateCompleted;
        
        /// <remarks/>
        public event getChangeDateCompletedEventHandler getChangeDateCompleted;
        
        /// <remarks/>
        public event setChangeDateCompletedEventHandler setChangeDateCompleted;
        
        /// <remarks/>
        public event getChangeTimeCompletedEventHandler getChangeTimeCompleted;
        
        /// <remarks/>
        public event setChangeTimeCompletedEventHandler setChangeTimeCompleted;
        
        /// <remarks/>
        public event setEmailCompletedEventHandler setEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStudentID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getStudentID() {
            object[] results = this.Invoke("getStudentID", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStudentIDAsync() {
            this.getStudentIDAsync(null);
        }
        
        /// <remarks/>
        public void getStudentIDAsync(object userState) {
            if ((this.getStudentIDOperationCompleted == null)) {
                this.getStudentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStudentIDOperationCompleted);
            }
            this.InvokeAsync("getStudentID", new object[0], this.getStudentIDOperationCompleted, userState);
        }
        
        private void OngetStudentIDOperationCompleted(object arg) {
            if ((this.getStudentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStudentIDCompleted(this, new getStudentIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setStudentID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setStudentID(string id) {
            this.Invoke("setStudentID", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void setStudentIDAsync(string id) {
            this.setStudentIDAsync(id, null);
        }
        
        /// <remarks/>
        public void setStudentIDAsync(string id, object userState) {
            if ((this.setStudentIDOperationCompleted == null)) {
                this.setStudentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetStudentIDOperationCompleted);
            }
            this.InvokeAsync("setStudentID", new object[] {
                        id}, this.setStudentIDOperationCompleted, userState);
        }
        
        private void OnsetStudentIDOperationCompleted(object arg) {
            if ((this.setStudentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setStudentIDCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFirstName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getFirstName() {
            object[] results = this.Invoke("getFirstName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFirstNameAsync() {
            this.getFirstNameAsync(null);
        }
        
        /// <remarks/>
        public void getFirstNameAsync(object userState) {
            if ((this.getFirstNameOperationCompleted == null)) {
                this.getFirstNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFirstNameOperationCompleted);
            }
            this.InvokeAsync("getFirstName", new object[0], this.getFirstNameOperationCompleted, userState);
        }
        
        private void OngetFirstNameOperationCompleted(object arg) {
            if ((this.getFirstNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFirstNameCompleted(this, new getFirstNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setFirstName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setFirstName(string fn) {
            this.Invoke("setFirstName", new object[] {
                        fn});
        }
        
        /// <remarks/>
        public void setFirstNameAsync(string fn) {
            this.setFirstNameAsync(fn, null);
        }
        
        /// <remarks/>
        public void setFirstNameAsync(string fn, object userState) {
            if ((this.setFirstNameOperationCompleted == null)) {
                this.setFirstNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetFirstNameOperationCompleted);
            }
            this.InvokeAsync("setFirstName", new object[] {
                        fn}, this.setFirstNameOperationCompleted, userState);
        }
        
        private void OnsetFirstNameOperationCompleted(object arg) {
            if ((this.setFirstNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setFirstNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLastName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLastName() {
            object[] results = this.Invoke("getLastName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLastNameAsync() {
            this.getLastNameAsync(null);
        }
        
        /// <remarks/>
        public void getLastNameAsync(object userState) {
            if ((this.getLastNameOperationCompleted == null)) {
                this.getLastNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastNameOperationCompleted);
            }
            this.InvokeAsync("getLastName", new object[0], this.getLastNameOperationCompleted, userState);
        }
        
        private void OngetLastNameOperationCompleted(object arg) {
            if ((this.getLastNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastNameCompleted(this, new getLastNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getEmail() {
            object[] results = this.Invoke("getEmail", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getEmailAsync() {
            this.getEmailAsync(null);
        }
        
        /// <remarks/>
        public void getEmailAsync(object userState) {
            if ((this.getEmailOperationCompleted == null)) {
                this.getEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmailOperationCompleted);
            }
            this.InvokeAsync("getEmail", new object[0], this.getEmailOperationCompleted, userState);
        }
        
        private void OngetEmailOperationCompleted(object arg) {
            if ((this.getEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmailCompleted(this, new getEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setLastName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setLastName(string ln) {
            this.Invoke("setLastName", new object[] {
                        ln});
        }
        
        /// <remarks/>
        public void setLastNameAsync(string ln) {
            this.setLastNameAsync(ln, null);
        }
        
        /// <remarks/>
        public void setLastNameAsync(string ln, object userState) {
            if ((this.setLastNameOperationCompleted == null)) {
                this.setLastNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetLastNameOperationCompleted);
            }
            this.InvokeAsync("setLastName", new object[] {
                        ln}, this.setLastNameOperationCompleted, userState);
        }
        
        private void OnsetLastNameOperationCompleted(object arg) {
            if ((this.setLastNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setLastNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDOB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDOB() {
            object[] results = this.Invoke("getDOB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDOBAsync() {
            this.getDOBAsync(null);
        }
        
        /// <remarks/>
        public void getDOBAsync(object userState) {
            if ((this.getDOBOperationCompleted == null)) {
                this.getDOBOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDOBOperationCompleted);
            }
            this.InvokeAsync("getDOB", new object[0], this.getDOBOperationCompleted, userState);
        }
        
        private void OngetDOBOperationCompleted(object arg) {
            if ((this.getDOBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDOBCompleted(this, new getDOBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setDOB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setDOB(string birth) {
            this.Invoke("setDOB", new object[] {
                        birth});
        }
        
        /// <remarks/>
        public void setDOBAsync(string birth) {
            this.setDOBAsync(birth, null);
        }
        
        /// <remarks/>
        public void setDOBAsync(string birth, object userState) {
            if ((this.setDOBOperationCompleted == null)) {
                this.setDOBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetDOBOperationCompleted);
            }
            this.InvokeAsync("setDOB", new object[] {
                        birth}, this.setDOBOperationCompleted, userState);
        }
        
        private void OnsetDOBOperationCompleted(object arg) {
            if ((this.setDOBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setDOBCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getGPA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getGPA() {
            object[] results = this.Invoke("getGPA", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGPAAsync() {
            this.getGPAAsync(null);
        }
        
        /// <remarks/>
        public void getGPAAsync(object userState) {
            if ((this.getGPAOperationCompleted == null)) {
                this.getGPAOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGPAOperationCompleted);
            }
            this.InvokeAsync("getGPA", new object[0], this.getGPAOperationCompleted, userState);
        }
        
        private void OngetGPAOperationCompleted(object arg) {
            if ((this.getGPACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGPACompleted(this, new getGPACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setGPA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setGPA(string grade) {
            this.Invoke("setGPA", new object[] {
                        grade});
        }
        
        /// <remarks/>
        public void setGPAAsync(string grade) {
            this.setGPAAsync(grade, null);
        }
        
        /// <remarks/>
        public void setGPAAsync(string grade, object userState) {
            if ((this.setGPAOperationCompleted == null)) {
                this.setGPAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetGPAOperationCompleted);
            }
            this.InvokeAsync("setGPA", new object[] {
                        grade}, this.setGPAOperationCompleted, userState);
        }
        
        private void OnsetGPAOperationCompleted(object arg) {
            if ((this.setGPACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setGPACompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMajorCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMajorCode() {
            object[] results = this.Invoke("getMajorCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMajorCodeAsync() {
            this.getMajorCodeAsync(null);
        }
        
        /// <remarks/>
        public void getMajorCodeAsync(object userState) {
            if ((this.getMajorCodeOperationCompleted == null)) {
                this.getMajorCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMajorCodeOperationCompleted);
            }
            this.InvokeAsync("getMajorCode", new object[0], this.getMajorCodeOperationCompleted, userState);
        }
        
        private void OngetMajorCodeOperationCompleted(object arg) {
            if ((this.getMajorCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMajorCodeCompleted(this, new getMajorCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setMajorCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setMajorCode(string mc) {
            this.Invoke("setMajorCode", new object[] {
                        mc});
        }
        
        /// <remarks/>
        public void setMajorCodeAsync(string mc) {
            this.setMajorCodeAsync(mc, null);
        }
        
        /// <remarks/>
        public void setMajorCodeAsync(string mc, object userState) {
            if ((this.setMajorCodeOperationCompleted == null)) {
                this.setMajorCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetMajorCodeOperationCompleted);
            }
            this.InvokeAsync("setMajorCode", new object[] {
                        mc}, this.setMajorCodeOperationCompleted, userState);
        }
        
        private void OnsetMajorCodeOperationCompleted(object arg) {
            if ((this.setMajorCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setMajorCodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAddDate() {
            object[] results = this.Invoke("getAddDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAddDateAsync() {
            this.getAddDateAsync(null);
        }
        
        /// <remarks/>
        public void getAddDateAsync(object userState) {
            if ((this.getAddDateOperationCompleted == null)) {
                this.getAddDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAddDateOperationCompleted);
            }
            this.InvokeAsync("getAddDate", new object[0], this.getAddDateOperationCompleted, userState);
        }
        
        private void OngetAddDateOperationCompleted(object arg) {
            if ((this.getAddDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAddDateCompleted(this, new getAddDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setAddDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setAddDate(string ad) {
            this.Invoke("setAddDate", new object[] {
                        ad});
        }
        
        /// <remarks/>
        public void setAddDateAsync(string ad) {
            this.setAddDateAsync(ad, null);
        }
        
        /// <remarks/>
        public void setAddDateAsync(string ad, object userState) {
            if ((this.setAddDateOperationCompleted == null)) {
                this.setAddDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetAddDateOperationCompleted);
            }
            this.InvokeAsync("setAddDate", new object[] {
                        ad}, this.setAddDateOperationCompleted, userState);
        }
        
        private void OnsetAddDateOperationCompleted(object arg) {
            if ((this.setAddDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setAddDateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getChangeDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getChangeDate() {
            object[] results = this.Invoke("getChangeDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getChangeDateAsync() {
            this.getChangeDateAsync(null);
        }
        
        /// <remarks/>
        public void getChangeDateAsync(object userState) {
            if ((this.getChangeDateOperationCompleted == null)) {
                this.getChangeDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChangeDateOperationCompleted);
            }
            this.InvokeAsync("getChangeDate", new object[0], this.getChangeDateOperationCompleted, userState);
        }
        
        private void OngetChangeDateOperationCompleted(object arg) {
            if ((this.getChangeDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChangeDateCompleted(this, new getChangeDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setChangeDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setChangeDate(string cd) {
            this.Invoke("setChangeDate", new object[] {
                        cd});
        }
        
        /// <remarks/>
        public void setChangeDateAsync(string cd) {
            this.setChangeDateAsync(cd, null);
        }
        
        /// <remarks/>
        public void setChangeDateAsync(string cd, object userState) {
            if ((this.setChangeDateOperationCompleted == null)) {
                this.setChangeDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetChangeDateOperationCompleted);
            }
            this.InvokeAsync("setChangeDate", new object[] {
                        cd}, this.setChangeDateOperationCompleted, userState);
        }
        
        private void OnsetChangeDateOperationCompleted(object arg) {
            if ((this.setChangeDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setChangeDateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getChangeTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getChangeTime() {
            object[] results = this.Invoke("getChangeTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getChangeTimeAsync() {
            this.getChangeTimeAsync(null);
        }
        
        /// <remarks/>
        public void getChangeTimeAsync(object userState) {
            if ((this.getChangeTimeOperationCompleted == null)) {
                this.getChangeTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChangeTimeOperationCompleted);
            }
            this.InvokeAsync("getChangeTime", new object[0], this.getChangeTimeOperationCompleted, userState);
        }
        
        private void OngetChangeTimeOperationCompleted(object arg) {
            if ((this.getChangeTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChangeTimeCompleted(this, new getChangeTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setChangeTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setChangeTime(string ct) {
            this.Invoke("setChangeTime", new object[] {
                        ct});
        }
        
        /// <remarks/>
        public void setChangeTimeAsync(string ct) {
            this.setChangeTimeAsync(ct, null);
        }
        
        /// <remarks/>
        public void setChangeTimeAsync(string ct, object userState) {
            if ((this.setChangeTimeOperationCompleted == null)) {
                this.setChangeTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetChangeTimeOperationCompleted);
            }
            this.InvokeAsync("setChangeTime", new object[] {
                        ct}, this.setChangeTimeOperationCompleted, userState);
        }
        
        private void OnsetChangeTimeOperationCompleted(object arg) {
            if ((this.setChangeTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setChangeTimeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setEmail(string e) {
            this.Invoke("setEmail", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void setEmailAsync(string e) {
            this.setEmailAsync(e, null);
        }
        
        /// <remarks/>
        public void setEmailAsync(string e, object userState) {
            if ((this.setEmailOperationCompleted == null)) {
                this.setEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetEmailOperationCompleted);
            }
            this.InvokeAsync("setEmail", new object[] {
                        e}, this.setEmailOperationCompleted, userState);
        }
        
        private void OnsetEmailOperationCompleted(object arg) {
            if ((this.setEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getStudentIDCompletedEventHandler(object sender, getStudentIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStudentIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStudentIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setStudentIDCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getFirstNameCompletedEventHandler(object sender, getFirstNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFirstNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFirstNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setFirstNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getLastNameCompletedEventHandler(object sender, getLastNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEmailCompletedEventHandler(object sender, getEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setLastNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getDOBCompletedEventHandler(object sender, getDOBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDOBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDOBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setDOBCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getGPACompletedEventHandler(object sender, getGPACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGPACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGPACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setGPACompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getMajorCodeCompletedEventHandler(object sender, getMajorCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMajorCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMajorCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setMajorCodeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAddDateCompletedEventHandler(object sender, getAddDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAddDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAddDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setAddDateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getChangeDateCompletedEventHandler(object sender, getChangeDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChangeDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChangeDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setChangeDateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getChangeTimeCompletedEventHandler(object sender, getChangeTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChangeTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChangeTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setChangeTimeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591